version: '3.4'

services:
  espnet:
    image: espnet
    build:
      context: .
      dockerfile: docker/Dockerfile.espnet
    # command: python embeddings_api.py
    ports:
      - "8001:8001"
    container_name: 'espnet-animespeech'
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]