version: '3.4'

services:
  espnet:
    image: espnet
    build:
      context: .
      dockerfile: docker/Dockerfile.espnet
    # command: python embeddings_api.py
    ports:
      - "8001:8001"
    container_name: 'espnet-animespeech'
    stdin_open: true
    tty: true
    volumes:
      # this copies the whole current directory into the app folder inside docker.
      # - ./:/app
      # - type: volume
      #   source: ./data/
      #   target: /animespeech/data
      # - type: volume
      #   source: ./src/
      #   target: /animespeech/src
      - ./data/:/animespeech/data
      - ./src/:/animespeech/src
      - ./tests/:/animespeech/tests
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  asr:
    image: reazonspeech
    build:
      context: .
      dockerfile: docker/Dockerfile.reazonspeech
    # command: python embeddings_api.py
    ports:
      - "8080:8080"
    container_name: 'reazonspeech-animespeech'
    stdin_open: true
    tty: true
    volumes:
      - ./data/:/animespeech/data
      - ./src/:/animespeech/src
      - ./tests/:/animespeech/tests
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  data:
  src:
  tests: